'use strict';
window.SIDE_B_DATA = {
  artists: [
    {id:'vivek',name:'Vivek Sagar',language:'Telugu',mood:'Warm',week:1,track:'Chinuku Taake',query:'Vivek Sagar Chinuku Taake Pelli Choopulu',note:'Playful Telugu melodies and relaxed arrangements: an easy first step from your language mix.'},
    {id:'justin',name:'Justin Prabhakaran',language:'Telugu',mood:'Warm',week:1,track:'Nee Neeli Kannullona',query:'Justin Prabhakaran Nee Neeli Kannullona',note:'Warm romantic melodies for the gentler side of your listening.'},
    {id:'govind',name:'Govind Vasantha',language:'Telugu',mood:'Reflective',week:1,track:'Life of Ram',query:'Govind Vasantha Life of Ram Jaanu',note:'Spacious, reflective music for winding down. Try both the Telugu and Tamil soundtracks.'},
    {id:'sean',name:'Sean Roldan',language:'Tamil',mood:'Warm',week:2,track:'Naan Gaali',query:'Sean Roldan Naan Gaali Good Night',note:'Earthy vocals and inviting melodies make an approachable Tamil discovery.'},
    {id:'pradeep',name:'Pradeep Kumar',language:'Tamil',mood:'Reflective',week:2,track:'Aval',query:'Pradeep Kumar Aval Manithan',note:'Expressive singing for the moments when you want feeling more than a big beat.'},
    {id:'santhosh',name:'Santhosh Narayanan',language:'Tamil',mood:'Warm',week:2,track:'Aasai Oru Pulveli',query:'Santhosh Narayanan Aasai Oru Pulveli',note:'A melodic starting point before exploring his more adventurous rhythms and textures.'},
    {id:'localtrain',name:'The Local Train',language:'Hindi',mood:'Energetic',week:3,track:'Aaftaab',query:'The Local Train Aaftaab official',note:'Emotional Hindi songwriting and guitar-driven builds, a step beyond film music.'},
    {id:'yellowdiary',name:'The Yellow Diary',language:'Hindi',mood:'Warm',week:3,track:'Roz Roz',query:'The Yellow Diary Roz Roz Shilpa Rao official',note:'Atmospheric indie pop with memorable vocal hooks. A gentle crossover from soundtracks.'},
    {id:'ritviz',name:'Ritviz',language:'Hindi',mood:'Energetic',week:3,track:'Udd Gaye',query:'Ritviz Udd Gaye official',note:'An energy experiment: Indian melodic influences meet electronic bounce.'},
    {id:'chai',name:'When Chai Met Toast',language:'English',mood:'Energetic',week:4,track:'Khoj',query:'When Chai Met Toast Khoj official',note:'Bright multilingual indie folk for an upbeat crossover week.'},
    {id:'prateek',name:'Prateek Kuhad',language:'English',mood:'Reflective',week:4,track:'cold/mess',query:'Prateek Kuhad cold mess official',note:'An intimate English-language direction alongside your Indian-language selections.'},
    {id:'anuv',name:'Anuv Jain',language:'Hindi',mood:'Reflective',week:4,track:'Baarishein',query:'Anuv Jain Baarishein official',note:'A quiet acoustic finish, with Hindi songwriting at the center.'}
  ],
  weeks:[{title:'Telugu melodies, room to explore',description:'Begin close to your confirmed language mix.'},{title:'Tamil warmth and distinctive voices',description:'Follow the voices, then explore the arrangements.'},{title:'Hindi songs beyond soundtracks',description:'Try indie guitars, atmospheric pop, and electronic rhythms.'},{title:'English and crossover listening',description:'Open the language mix, then end on a gentle acoustic note.'}],
  mixes:[{title:'Window Seat',subtitle:'Familiar melodies',note:'Soft vocals and an easy evening pace.',tracks:[['A.R. Rahman','New York Nagaram'],['Harris Jayaraj','Nenjukkul Peidhidum'],['Mani Sharma','Avunu Nijam Athadu'],['Pritam','Iktara Wake Up Sid'],['Coldplay','Sparks']]},{title:'Sing-Along Drive',subtitle:'Timeless hooks',note:'Nostalgia, movement, and a gradual lift in energy.',tracks:[['Michael Jackson','Rock With You'],['Backstreet Boys','I Want It That Way'],['A.R. Rahman','Chaiyya Chaiyya'],['Harris Jayaraj','June Ponal Unnale Unnale'],['Devi Sri Prasad','Uppenantha Arya 2']]}]
};
