import assert from 'node:assert/strict';
import {tasteProfile,parseSongs,messagesFor} from '../ai-core.mjs';
import {recommend,stop} from '../ai-client.mjs';
const state={imports:[{artist:'Playlist-only artist',title:'Private imported title'}],seeds:[],ratings:{legacy:{name:'New Artist',value:'skip'}},songRatings:{a:{artist:'New Artist',title:'Disliked song',value:'skip',at:2},b:{artist:'A.R. Rahman',title:'Liked song',value:'replay',at:1}},filters:{language:'Tamil',mood:'Warm'},rotation:1};
const profile={...tasteProfile(state),candidates:[{artist:'New Artist',title:'Different song',language:'Tamil',mood:'Warm'}]};
assert.equal(profile.provisional,false);
assert(messagesFor(profile)[1].content.includes('Liked song'));
assert(!messagesFor(profile)[1].content.includes('Private imported title'));
assert(!messagesFor(profile)[1].content.includes('legacy'));
const pick={artist:'New Artist',title:'Different song',language:'Tamil',mood:'Warm',reason:'Similar gentle melody to Liked song.'};
const parsed=parseSongs('{"ids":[1,1,999]}',profile);
assert.equal(parsed.length,1);assert.equal(parsed[0].title,'Different song');
assert.throws(()=>parseSongs('not json',profile));
assert.throws(()=>parseSongs('{"songs":[{"artist":"Fake"}]}',profile));
assert.throws(()=>messagesFor({...profile,candidates:undefined}),/Verified candidates/);
assert.equal(tasteProfile({...state,songRatings:{}}).provisional,true);
Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});
await assert.rejects(recommend(profile,()=>{},new AbortController().signal),/does not support/);
navigator.gpu={requestAdapter:async()=>({features:new Set()})};
await assert.rejects(recommend(profile,()=>{},new AbortController().signal),/cannot run/);
navigator.gpu={requestAdapter:async()=>({features:new Set(['shader-f16'])})};
let instance,hang=false;
globalThis.Worker=class {constructor(){instance=this;}terminate(){this.terminated=true;}postMessage(){if(!hang)queueMicrotask(()=>this.onmessage({data:{type:'result',songs:parsed}}));}};
assert.deepEqual(await recommend(profile,()=>{},new AbortController().signal),parsed);
hang=true;const c=new AbortController(),pending=recommend(profile,()=>{},c.signal);
await new Promise(r=>setImmediate(r));c.abort();await assert.rejects(pending,/stopped/);assert(instance.terminated);
hang=false;assert.deepEqual(await recommend(profile,()=>{},new AbortController().signal),parsed);stop();
console.log('PASS: taste inputs, strict AI output validation, exclusions, filters, unsupported GPU, cancellation and recovery.');
