import assert from 'node:assert/strict';
import {tasteProfile,parseArtists,messagesFor} from '../ai-core.mjs';
import {recommend,stop} from '../ai-client.mjs';
const state={imports:[{artist:'A.R. Rahman',title:'Test song'}],seeds:[],ratings:{x:{name:'Skipped Artist',value:'skip'}},filters:{language:'Tamil',mood:'Warm'},rotation:1};
const profile=tasteProfile(state);
assert.equal(profile.provisional,false);
assert.equal(profile.playlistArtists[0].artist,'A.R. Rahman');
assert(messagesFor(profile)[1].content.includes('A.R. Rahman'));
const pick={name:'New Artist',language:'Tamil',mood:'Warm',reason:'Similar gentle melodies.'};
const parsed=parseArtists(JSON.stringify({artists:[pick,pick,{...pick,name:'Skipped Artist'},{...pick,name:'Wrong language',language:'English'}]}),profile);
assert.equal(parsed.length,1);
assert.throws(()=>parseArtists('not json',profile));
assert.throws(()=>parseArtists('{"artists":[{"name":"Fake"}]}',profile));
assert.throws(()=>parseArtists(JSON.stringify({artists:[{...pick,mood:'Energetic'}]}),profile));
assert.equal(tasteProfile({...state,imports:[],ratings:{}}).provisional,true);
Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});
await assert.rejects(recommend(profile,()=>{},new AbortController().signal),/does not support/);
navigator.gpu={requestAdapter:async()=>({features:new Set()})};
await assert.rejects(recommend(profile,()=>{},new AbortController().signal),/cannot run/);
navigator.gpu={requestAdapter:async()=>({features:new Set(['shader-f16'])})};
let instance,hang=false;
globalThis.Worker=class {constructor(){instance=this;}terminate(){this.terminated=true;}postMessage(){if(!hang)queueMicrotask(()=>this.onmessage({data:{type:'result',artists:parsed}}));}};
assert.deepEqual(await recommend(profile,()=>{},new AbortController().signal),parsed);
hang=true;const c=new AbortController(),pending=recommend(profile,()=>{},c.signal);
await new Promise(r=>setImmediate(r));c.abort();await assert.rejects(pending,/stopped/);assert(instance.terminated);
hang=false;assert.deepEqual(await recommend(profile,()=>{},new AbortController().signal),parsed);stop();
console.log('PASS: taste inputs, strict AI output validation, exclusions, filters, unsupported GPU, cancellation and recovery.');
